import { COLLECTION_NAMES } from "../contracts.js";
import type { StyleflowTokensFile } from "../format/index.js";
import { typographyTextStyles } from "./contractOutput.js";
import { cssSlug, TokenModel } from "./model.js";

export interface BaseCssOptions {
  utilities?: boolean;
  typography?: boolean;
}

export function generateBaseCss(tokens: StyleflowTokensFile, options: BaseCssOptions = {}): string {
  const chunks = ["/* Generated by StyleFlow. Base utilities and typography defaults. */"];
  if (options.utilities !== false) {
    chunks.push(utilityCss());
  }
  if (options.typography !== false) {
    chunks.push(typographyBridgeCss(tokens), typographyBaseCss());
  }
  return `${chunks.filter(Boolean).join("\n\n")}\n`;
}

export function generateTypographyOverrideCss(tokens: StyleflowTokensFile): string {
  const model = new TokenModel(tokens);
  const value = (name: string, fallback: string) => typographyCssValue(model, name, fallback);
  return `/* StyleFlow typography overrides.
 * This file is created once and is not overwritten by styleflow build.
 * Import it after .styleflow/runtime.css and .styleflow/base.css.
 */
:root {
  --sf-font-body: ${value("body/default/body-md/family", "Inter, Arial, sans-serif")};
  --sf-font-heading: ${value("heading/default/heading-2/family", "Inter, Arial, sans-serif")};
  --sf-weight-body: ${value("body/default/body-md/weight", "400")};
  --sf-weight-heading: ${value("heading/default/heading-2/weight", "700")};
  --sf-leading-body: ${value("body/default/body-md/line-height", "24px")};
  --sf-leading-heading: ${value("heading/default/heading-2/line-height", "40px")};
}
`;
}

function utilityCss(): string {
  return `@layer components {
  .sf-ui {
    border-radius: var(--local-radius);
    padding-block: var(--local-py);
    padding-inline: var(--local-px);
    gap: var(--local-gap);
  }

  .sf-surface,
  .sf-panel,
  .sf-control,
  .sf-field,
  .sf-badge {
    border: var(--local-border-width) solid var(--local-border);
    background: var(--local-surface);
    color: var(--local-foreground-primary);
  }

  .sf-surface[data-no-border],
  .sf-ui[data-no-border] {
    border: none;
  }

  .sf-surface[data-no-bg] {
    background: transparent;
  }

  .sf-ui[data-no-gap] {
    gap: 0;
  }

  .sf-ui[data-no-radius] {
    border-radius: 0;
  }

  .sf-ui[data-no-padding] {
    padding: 0;
  }

  .sf-control {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    inline-size: fit-content;
    text-align: center;
    text-decoration: none;
    cursor: pointer;
  }

  .sf-control:disabled,
  .sf-control[aria-disabled="true"] {
    cursor: not-allowed;
  }

  .sf-field {
    inline-size: 100%;
  }

  .sf-text {
    color: var(--local-foreground-primary);
  }

  .sf-badge {
    display: inline-flex;
    align-items: center;
    white-space: nowrap;
  }
}

@layer utilities {
  [data-foreground="primary"] {
    color: var(--local-foreground-primary);
  }

  [data-foreground="accent"] {
    color: var(--local-foreground-accent);
  }

  [data-foreground="secondary"] {
    color: var(--local-foreground-secondary);
  }

  [data-foreground="tertiary"] {
    color: var(--local-foreground-tertiary);
  }

  [data-foreground="muted"] {
    color: var(--local-foreground-muted);
  }
}`;
}

function typographyBridgeCss(tokens: StyleflowTokensFile): string {
  const model = new TokenModel(tokens);
  const declarations: string[] = [];

  for (const style of typographyTextStyles(tokens)) {
    const prefix = cssSlug(style.tokenPrefix);
    const isHeading = style.group === "heading";
    declarations.push(`  --typography-${prefix}-family: var(--sf-font-${isHeading ? "heading" : "body"}, ${typographyCssValue(model, `${style.tokenPrefix}/family`, "Inter, Arial, sans-serif")});`);
    declarations.push(`  --typography-${prefix}-weight: var(--sf-weight-${isHeading ? "heading" : "body"}, ${typographyCssValue(model, `${style.tokenPrefix}/weight`, "400")});`);
    declarations.push(`  --typography-${prefix}-line-height: var(--sf-leading-${isHeading ? "heading" : "body"}, ${typographyCssValue(model, `${style.tokenPrefix}/line-height`, "1.5")});`);
  }

  return `:root {\n${declarations.join("\n")}\n}`;
}

function typographyBaseCss(): string {
  return `@layer base {
  body {
    font-family: var(--typography-body-default-body-md-family, Inter, Arial, sans-serif);
    font-size: var(--typography-body-default-body-md-size, 1rem);
    font-weight: var(--typography-body-default-body-md-weight, 400);
    line-height: var(--typography-body-default-body-md-line-height, 1.5);
  }

  :is(.display-1, .display-2, .display-3, .heading-1, .heading-2, .heading-3, .heading-4, .heading-5, .heading-6, h1, h2, h3, h4, h5, h6) {
    margin: 0;
    font-family: var(--typography-heading-default-heading-2-family, Inter, Arial, sans-serif);
    font-weight: var(--typography-heading-default-heading-2-weight, 700);
    color: var(--local-foreground-primary);
  }

  .display-1 {
    font-size: var(--typography-heading-default-heading-0-size, 4rem);
    line-height: var(--typography-heading-default-heading-0-line-height, 1.05);
  }

  .display-2 {
    font-size: var(--typography-heading-default-heading-1-size, 3rem);
    line-height: var(--typography-heading-default-heading-1-line-height, 1.08);
  }

  .display-3,
  h1,
  .heading-1 {
    font-size: var(--typography-heading-default-heading-1-size, 3rem);
    line-height: var(--typography-heading-default-heading-1-line-height, 1.08);
  }

  h2,
  .heading-2 {
    font-size: var(--typography-heading-default-heading-2-size, 2.25rem);
    line-height: var(--typography-heading-default-heading-2-line-height, 1.12);
  }

  h3,
  .heading-3 {
    font-size: var(--typography-heading-default-heading-3-size, 1.75rem);
    line-height: var(--typography-heading-default-heading-3-line-height, 1.16);
  }

  h4,
  .heading-4 {
    font-size: var(--typography-heading-default-heading-4-size, 1.35rem);
    line-height: var(--typography-heading-default-heading-4-line-height, 1.2);
  }

  h5,
  .heading-5 {
    font-size: var(--typography-heading-default-heading-5-size, 1.15rem);
    line-height: var(--typography-heading-default-heading-5-line-height, 1.25);
  }

  h6,
  .heading-6 {
    font-size: var(--typography-heading-default-heading-6-size, 1rem);
    line-height: var(--typography-heading-default-heading-6-line-height, 1.3);
  }

  .body-lg {
    font-size: var(--typography-body-default-body-lg-size, 1.125rem);
    line-height: var(--typography-body-default-body-lg-line-height, 1.5);
  }

  .body-md {
    font-size: var(--typography-body-default-body-md-size, 1rem);
    line-height: var(--typography-body-default-body-md-line-height, 1.5);
  }

  .body-sm {
    font-size: var(--typography-body-default-body-sm-size, 0.875rem);
    line-height: var(--typography-body-default-body-sm-line-height, 1.5);
  }

  .body-xs {
    font-size: var(--typography-body-default-body-xs-size, 0.75rem);
    line-height: var(--typography-body-default-body-xs-line-height, 1.5);
  }
}`;
}

function typographyCssValue(model: TokenModel, name: string, fallback: string): string {
  const number = model.resolveNumber(COLLECTION_NAMES.typography, name, "Base");
  if (number !== undefined) {
    return name.endsWith("/weight") ? trimNumber(number) : `${trimNumber(number)}px`;
  }
  const string = model.resolveString(COLLECTION_NAMES.typography, name, "Base");
  return string ? JSON.stringify(string) : fallback;
}

function trimNumber(value: number): string {
  return Number(value.toFixed(4)).toString();
}
