import {
  COLLECTION_NAMES,
  COLOR_INTENSITIES,
  COLOR_TONES,
  LAYOUT_DENSITIES,
  LAYOUT_ROLES,
  SURFACE_TYPES,
  THEME_MODES
} from "../contracts.js";
import type { StyleflowTokensFile } from "../format/index.js";
import { cssSlug } from "./model.js";

export interface StyleflowTextStyleContract {
  id: string;
  label: string;
  group: string;
  variant: string;
  role: string;
  tokenPrefix: string;
}

export interface StyleflowPublicContract {
  version: string;
  tones: string[];
  intensities: string[];
  layoutRoles: string[];
  densities: string[];
  themes: string[];
  surfaceTypes: string[];
  textStyles: StyleflowTextStyleContract[];
}

export function publicContract(tokens: StyleflowTokensFile): StyleflowPublicContract {
  return {
    version: tokens.version,
    tones: modes(tokens, COLLECTION_NAMES.colorTone, COLOR_TONES),
    intensities: modes(tokens, COLLECTION_NAMES.colorIntensity, COLOR_INTENSITIES),
    layoutRoles: modes(tokens, COLLECTION_NAMES.layoutRole, LAYOUT_ROLES),
    densities: modes(tokens, COLLECTION_NAMES.layoutRoleDensity, LAYOUT_DENSITIES),
    themes: modes(tokens, COLLECTION_NAMES.semanticColor, THEME_MODES),
    surfaceTypes: SURFACE_TYPES.slice(),
    textStyles: typographyTextStyles(tokens)
  };
}

export function generateContractJson(tokens: StyleflowTokensFile): string {
  return `${JSON.stringify(publicContract(tokens), null, 2)}\n`;
}

export function generateContractTs(tokens: StyleflowTokensFile): string {
  const contract = publicContract(tokens);
  return `/* Generated by StyleFlow. Public runtime contract values. */
export const styleflowContract = ${JSON.stringify(contract, null, 2)} as const;

export const styleflowTones = styleflowContract.tones;
export const styleflowIntensities = styleflowContract.intensities;
export const styleflowLayoutRoles = styleflowContract.layoutRoles;
export const styleflowDensities = styleflowContract.densities;
export const styleflowThemes = styleflowContract.themes;
export const styleflowSurfaceTypes = styleflowContract.surfaceTypes;
export const styleflowTextStyles = styleflowContract.textStyles;

export default {
  styleflowContract,
  styleflowTones,
  styleflowIntensities,
  styleflowLayoutRoles,
  styleflowDensities,
  styleflowThemes,
  styleflowSurfaceTypes,
  styleflowTextStyles
};

export type StyleflowTone = (typeof styleflowTones)[number];
export type StyleflowIntensityString = (typeof styleflowIntensities)[number];
export type StyleflowIntensity = StyleflowIntensityString | ${contract.intensities.join(" | ")};
export type StyleflowLayoutRole = (typeof styleflowLayoutRoles)[number];
export type StyleflowDensity = (typeof styleflowDensities)[number];
export type StyleflowTheme = (typeof styleflowThemes)[number];
export type StyleflowSurfaceType = (typeof styleflowSurfaceTypes)[number];
export type StyleflowTextStyleId = (typeof styleflowTextStyles)[number]["id"];
`;
}

export function typographyTextStyles(tokens: StyleflowTokensFile): StyleflowTextStyleContract[] {
  const collection = tokens.collections.find((item) => item.name === COLLECTION_NAMES.typography);
  if (!collection) {
    return [];
  }

  const prefixes = new Map<string, Set<string>>();
  for (const variable of collection.variables) {
    const match = variable.name.match(/^(.+)\/(family|line-height|size|style|weight)$/);
    if (!match) {
      continue;
    }

    const [, prefix, property] = match;
    const properties = prefixes.get(prefix) ?? new Set<string>();
    properties.add(property);
    prefixes.set(prefix, properties);
  }

  return Array.from(prefixes.entries())
    .filter(([, properties]) => properties.has("size") && properties.has("line-height"))
    .map(([prefix]) => {
      const [group = "text", variant = "default", role = prefix] = prefix.split("/");
      return {
        id: cssSlug(prefix),
        label: labelFromPrefix(prefix),
        group,
        variant,
        role,
        tokenPrefix: prefix
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

function modes<T extends string>(tokens: StyleflowTokensFile, collectionName: string, supported: readonly T[]): T[] {
  const collection = tokens.collections.find((item) => item.name === collectionName);
  return supported.filter((mode) => collection?.modes.includes(mode));
}

function labelFromPrefix(prefix: string): string {
  return prefix
    .split("/")
    .flatMap((part) => part.split("-"))
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
