export interface StyleflowEntrySections {
  theme?: string;
  tokens?: string;
  runtime: string;
  base?: string;
}

/**
 * Genera l'unico entry point `styleflow.css`: concatena INLINE le sezioni
 * (theme bridge → token legacy opzionale → runtime → base) in un singolo file.
 *
 * Concatenazione inline (non `@import` annidati) di proposito: garantisce che il
 * blocco `@theme inline` di theme.css resti top-level e venga processato da
 * Tailwind v4 anche quando il progetto importa solo questo file. Va importato
 * DOPO `@import "tailwindcss";`.
 */
export function generateStyleflowCss(sections: StyleflowEntrySections): string {
  const header =
    "/* Generated by StyleFlow. Single entry point.\n" +
    " * Import ONLY this file in your app, after `@import \"tailwindcss\";`.\n" +
    " * Bundles (in order): Tailwind @theme bridge, runtime tokens + resolvers, base utilities. */";
  const parts = [sections.theme, sections.tokens, sections.runtime, sections.base]
    .filter((part): part is string => Boolean(part && part.trim().length > 0));
  return `${[header, ...parts].join("\n\n")}\n`;
}
