import {
  BREAKPOINTS,
  COLLECTION_NAMES,
  COLOR_INTENSITIES,
  COLOR_TONES,
  INTERACTION_STATES,
  LAYOUT_DENSITIES,
  LAYOUT_ROLES,
  LOCAL_COLOR_ROLES,
  LOCAL_LAYOUT_PROPERTIES,
  THEME_MODES
} from "../contracts.js";
import type { StyleflowTokensFile } from "../format/index.js";
import { typographyTextStyles } from "./contractOutput.js";
import { cssSlug, tokenKey, TokenModel, valueToCss, type InternalTokenNameMode } from "./model.js";
import { tokenDependencyClosure, tokenValueReferenceKeys } from "./tokensCss.js";
import type { RuntimeUsage } from "./usage.js";

const staticRole: Record<(typeof LOCAL_COLOR_ROLES)[number], string> = {
  surface: "background",
  "surface-scrim": "surface-scrim",
  border: "border",
  "border-soft": "border-soft",
  "border-strong": "border-strong",
  "border-accent": "border-accent",
  "foreground-primary": "foreground-primary",
  "foreground-secondary": "foreground-secondary",
  "foreground-tertiary": "foreground-tertiary",
  "foreground-muted": "foreground-muted",
  "foreground-accent": "foreground-accent"
};

const interactiveRole = {
  surface: "background",
  border: "border",
  "foreground-primary": "foreground",
  "border-accent": "focus-ring"
} as const;

const interactivePriority = {
  "interactive-primary": { priority: "primary", variant: "strong" },
  "interactive-secondary": { priority: "secondary", variant: "soft" },
  "interactive-tertiary": { priority: "tertiary", variant: "soft" }
} as const;

export interface RuntimeCssOutput {
  css: string;
  tokenKeys: Set<string>;
}

export interface RuntimeCssOptions {
  /** Collassa i layer alias trasparenti (default true). Vedi TokenModel. */
  transparent?: boolean;
  /** Nomi delle custom property interne emesse dal runtime. */
  internalTokenNames?: InternalTokenNameMode;
}

export function generateRuntimeCss(tokens: StyleflowTokensFile, usage?: RuntimeUsage, options?: RuntimeCssOptions): string {
  return generateRuntimeCssOutput(tokens, usage, options).css;
}

export function generateRuntimeCssOutput(tokens: StyleflowTokensFile, usage?: RuntimeUsage, options: RuntimeCssOptions = {}): RuntimeCssOutput {
  const model = new TokenModel(tokens, { transparent: options.transparent !== false, internalTokenNames: options.internalTokenNames });
  const roots = new Set<string>();
  const resolverChunks = [
    ...breakpointResolvers(model, roots, usage),
    ...rootDefaults(model, roots, usage),
    ...axisResolvers(model, roots, usage),
    ...surfaceResolvers(model, roots, usage),
    ...typographyProperties(model, roots, usage),
    ...textStyleResolvers(model, usage)
  ].filter(Boolean);
  const chunks: string[] = ["/* Generated by StyleFlow. Public runtime contract. */"];
  const included = usage ? tokenDependencyClosure(tokens, roots, true, model.transparent) : undefined;
  chunks.push(...themeResolvers(model, usage, included, roots));
  chunks.push(...resolverChunks);
  const css = `${dedupeChunks(chunks).join("\n\n")}\n`;
  return {
    css,
    tokenKeys: usage ? tokenDependencyClosure(tokens, roots, true, model.transparent) : new Set<string>()
  };
}

function themeResolvers(model: TokenModel, usage?: RuntimeUsage, included?: ReadonlySet<string>, roots?: Set<string>): string[] {
  return model.source.collections
    .filter((collection) => collection.modes.length > 0 && collection.modes.every((mode) => THEME_MODES.includes(mode as never)))
    .flatMap((collection) => {
      const variables = included
        ? collection.variables.filter((variable) => included.has(tokenKey(collection.name, variable.name)))
        : collection.variables;
      if (variables.length === 0) {
        return [];
      }
      const defaultTheme = collection.modes.includes("light") ? "light" : "dark";
      const chunks = [
        cssBlock(`:root,\n[data-theme="${defaultTheme}"]`, variables.map((variable) => {
          addValueReferences(model, roots, collection.name, variable.name, defaultTheme);
          return valueDeclaration(model.cssTokenName(collection.name, variable.name), valueToCss(collection, variable, variable.valuesByMode[defaultTheme], model, defaultTheme));
        }))
      ];
      for (const theme of collection.modes.filter((mode) => mode !== defaultTheme)) {
        if (!usage || usage.themes.has(theme as never)) {
          chunks.push(cssBlock(`[data-theme="${theme}"]`, variables.map((variable) => {
            addValueReferences(model, roots, collection.name, variable.name, theme);
            return valueDeclaration(model.cssTokenName(collection.name, variable.name), valueToCss(collection, variable, variable.valuesByMode[theme], model, theme));
          })));
        }
      }
      return chunks;
    });
}

function breakpointResolvers(model: TokenModel, roots: Set<string>, usage?: RuntimeUsage): string[] {
  const collection = model.collection(COLLECTION_NAMES.breakpoints);
  if (!collection) {
    return [];
  }
  const filter = breakpointVariableFilter(usage);
  const baseDeclarations = modeDeclarations(collection.name, "xs", model, roots, filter);
  const chunks = [cssBlock(":root", baseDeclarations)];
  let previous = declarationMap(baseDeclarations);
  for (const breakpoint of BREAKPOINTS.slice(1)) {
    const min = model.resolveNumber(COLLECTION_NAMES.primitives, `dimension/primitive/breakpoint/${breakpoint}`, "Base");
    if (min !== undefined) {
      const declarations = modeDeclarations(collection.name, breakpoint, model, roots, filter);
      const changed = declarations.filter((declaration) => previous.get(declarationName(declaration)) !== declaration);
      previous = declarationMap(declarations);
      if (changed.length > 0) {
        chunks.push(`@media (min-width: ${min}px) {\n${indent(cssBlock(":root", changed))}\n}`);
      }
    }
  }
  return chunks;
}

// I valori di default di ogni asse (tone=neutral, intensity=1, density=md, role=none)
// sono il baseline su :root, ma vanno anche resettabili esplicitamente quando il
// valore di default è annidato sotto un valore non-default (es. data-color-tone="neutral"
// dentro un antenato data-color-tone="accent"): senza un blocco [data-...="<default>"]
// le custom property continuerebbero a ereditare i valori dell'antenato.
// Stessa soluzione già adottata per il tema (`:root,\n[data-theme="..."]`). I selettori
// combinati lasciano invariato l'insieme di dichiarazioni che matchano :root (zero byte
// duplicati) e ogni blocco trasporta le stesse companion declarations del gemello in
// axisResolvers (colorLocals con l'intensità, layoutLocals con il ruolo).
function rootDefaults(model: TokenModel, roots: Set<string>, usage?: RuntimeUsage): string[] {
  return [
    cssBlock(`:root,\n[data-color-tone="neutral"]`,
      modeDeclarations(COLLECTION_NAMES.colorTone, "neutral", model, roots, colorToneVariableFilter(usage))),
    cssBlock(`:root,\n[data-color-intensity="1"]`, [
      ...modeDeclarations(COLLECTION_NAMES.colorIntensity, "1", model, roots, colorIntensityVariableFilter(usage)),
      ...colorLocals(model, roots)
    ]),
    cssBlock(`:root,\n[data-layout-density="md"]`,
      modeDeclarations(COLLECTION_NAMES.layoutRoleDensity, "md", model, roots, layoutDensityVariableFilter(usage))),
    cssBlock(`:root,\n[data-layout-role="none"]`, [
      ...modeDeclarations(COLLECTION_NAMES.layoutRole, "none", model, roots),
      ...layoutLocals(model, roots)
    ])
  ];
}

function axisResolvers(model: TokenModel, roots: Set<string>, usage?: RuntimeUsage): string[] {
  const chunks: string[] = [];
  for (const tone of selectedValues(activeModes(model, COLLECTION_NAMES.colorTone, COLOR_TONES), usage?.tones)) {
    if (tone !== "neutral") {
      chunks.push(modeSelectionBlock(`[data-color-tone="${tone}"]`, COLLECTION_NAMES.colorTone, tone, model, roots, colorToneVariableFilter(usage)));
    }
  }
  for (const intensity of selectedValues(activeModes(model, COLLECTION_NAMES.colorIntensity, COLOR_INTENSITIES), usage?.intensities)) {
    if (intensity !== "1") {
      chunks.push(cssBlock(`[data-color-intensity="${intensity}"]`, [
        ...modeDeclarations(COLLECTION_NAMES.colorIntensity, intensity, model, roots, colorIntensityVariableFilter(usage)),
        ...colorLocals(model, roots)
      ]));
    }
  }
  for (const density of selectedValues(activeModes(model, COLLECTION_NAMES.layoutRoleDensity, LAYOUT_DENSITIES), usage?.densities)) {
    if (density !== "md") {
      chunks.push(modeSelectionBlock(`[data-layout-density="${density}"]`, COLLECTION_NAMES.layoutRoleDensity, density, model, roots, layoutDensityVariableFilter(usage)));
    }
  }
  for (const role of selectedValues(activeModes(model, COLLECTION_NAMES.layoutRole, LAYOUT_ROLES), usage?.layoutRoles)) {
    if (role !== "none") {
      chunks.push(cssBlock(`[data-layout-role="${role}"]`, [
        ...modeDeclarations(COLLECTION_NAMES.layoutRole, role, model, roots),
        ...layoutLocals(model, roots)
      ]));
    }
  }
  return chunks;
}

function surfaceResolvers(model: TokenModel, roots: Set<string>, usage?: RuntimeUsage): string[] {
  const chunks: string[] = [];
  for (const kind of selectedStaticSurfaces(usage)) {
    for (const role of LOCAL_COLOR_ROLES) {
      addReference(roots, COLLECTION_NAMES.colorIntensity, `on-surface/static/${kind}/${staticRole[role]}`);
    }
    chunks.push(cssBlock(`[data-surface-type="${kind}"]`, LOCAL_COLOR_ROLES.map((role) =>
      `  --local-${role}: var(${model.cssTokenName(COLLECTION_NAMES.colorIntensity, `on-surface/static/${kind}/${staticRole[role]}`)});`)));
  }
  for (const [surface, options] of selectedInteractiveSurfaces(usage)) {
    chunks.push(interactiveSurfaceBlock(model, roots, surface, options.priority, "default", ""));
    chunks.push(interactiveSurfaceBlock(model, roots, surface, options.priority, "hover", `:hover:not([data-interaction-state])`));
    chunks.push(interactiveSurfaceBlock(model, roots, surface, options.priority, "active", `:active:not([data-interaction-state])`));
    chunks.push(interactiveSurfaceBlock(model, roots, surface, options.priority, "focus", `:focus-visible:not([data-interaction-state])`));
    chunks.push(interactiveSurfaceBlock(model, roots, surface, options.priority, "disabled", `:disabled:not([data-interaction-state]),\n[data-surface-type="${surface}"][aria-disabled="true"]:not([data-interaction-state])`));
    for (const state of INTERACTION_STATES) {
      chunks.push(interactiveSurfaceBlock(model, roots, surface, options.priority, state, `[data-interaction-state="${state}"]`));
    }
  }
  return chunks;
}

function interactiveSurfaceBlock(model: TokenModel, roots: Set<string>, surface: string, priority: string, state: string, suffix: string): string {
  const selector = suffix.startsWith("[") ? `[data-surface-type="${surface}"]${suffix}` : `[data-surface-type="${surface}"]${suffix}`;
  for (const source of Object.values(interactiveRole)) {
    addReference(roots, COLLECTION_NAMES.colorIntensity, `on-surface/interactive/${priority}/${state}/${source}`);
  }
  const declarations = Object.entries(interactiveRole).map(([local, source]) =>
    `  --local-${local}: var(${model.cssTokenName(COLLECTION_NAMES.colorIntensity, `on-surface/interactive/${priority}/${state}/${source}`)});`);
  return cssBlock(selector, declarations);
}

function typographyProperties(model: TokenModel, roots: Set<string>, usage?: RuntimeUsage): string[] {
  const collection = model.collection(COLLECTION_NAMES.typography);
  if (!collection) {
    return [];
  }
  const variables = usage
    ? collection.variables.filter((variable) => {
        const publicName = `--typography-${cssSlug(variable.name)}`;
        if (usage.typographyVariables.has(publicName)) {
          return true;
        }

        const prefix = typographyPrefix(variable.name);
        return prefix !== "" && selectedTextStyleIds(model, usage).has(cssSlug(prefix));
      })
    : collection.variables;
  if (variables.length === 0) {
    return [];
  }
  const declarations = variables.map((variable) => {
    const publicName = `--typography-${cssSlug(variable.name)}`;
    if (variable.name.endsWith("/weight")) {
      const weight = model.resolveNumber(COLLECTION_NAMES.typography, variable.name, "Base")
        ?? fontWeight(model.resolveString(COLLECTION_NAMES.typography, variable.name, "Base") ?? "Regular");
      return `  ${publicName}: ${weight};`;
    }
    if (variable.name.endsWith("/style")) {
      const style = model.resolveString(COLLECTION_NAMES.typography, variable.name, "Base") ?? "normal";
      return `  ${publicName}: ${cssSlug(style) || "normal"};`;
    }
    addValueReferences(model, roots, collection.name, variable.name, "Base");
    return valueDeclaration(publicName, valueToCss(collection, variable, variable.valuesByMode.Base, model, "Base"));
  });
  return [cssBlock(":root", declarations)];
}

function textStyleResolvers(model: TokenModel, usage?: RuntimeUsage): string[] {
  const styles = typographyTextStyles(model.source).filter((style) => {
    if (!usage || usage.textStyles.has("*")) {
      return true;
    }
    return usage.textStyles.has(style.id);
  });

  return styles.map((style) => {
    const prefix = cssSlug(style.tokenPrefix);
    return cssBlock(`[data-text-style="${style.id}"]`, [
      `  font-family: var(--typography-${prefix}-family);`,
      `  font-size: var(--typography-${prefix}-size);`,
      `  font-style: var(--typography-${prefix}-style);`,
      `  font-weight: var(--typography-${prefix}-weight);`,
      `  line-height: var(--typography-${prefix}-line-height);`
    ]);
  });
}

function selectedTextStyleIds(model: TokenModel, usage: RuntimeUsage): Set<string> {
  const styles = typographyTextStyles(model.source).map((style) => style.id);
  return usage.textStyles.has("*")
    ? new Set(styles)
    : new Set(styles.filter((style) => usage.textStyles.has(style)));
}

function typographyPrefix(variableName: string): string {
  const match = variableName.match(/^(.+)\/(family|line-height|size|style|weight)$/);
  return match?.[1] ?? "";
}

function fontWeight(value: string): number {
  const normalized = value.toLowerCase().replace(/\s+/g, "");
  return ({ thin: 100, extralight: 200, light: 300, regular: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800, black: 900 } as Record<string, number>)[normalized] ?? 400;
}

function colorLocals(model: TokenModel, roots: Set<string>): string[] {
  return LOCAL_COLOR_ROLES.map((role) => {
    addReference(roots, COLLECTION_NAMES.colorIntensity, `local/${role}`);
    return `  --local-${role}: var(${model.cssTokenName(COLLECTION_NAMES.colorIntensity, `local/${role}`)});`;
  });
}

function layoutLocals(model: TokenModel, roots: Set<string>): string[] {
  return LOCAL_LAYOUT_PROPERTIES.map((property) => {
    const local = property === "padding-x" ? "px" : property === "padding-y" ? "py" : property;
    addReference(roots, COLLECTION_NAMES.layoutRole, property);
    return `  --local-${local}: var(${model.cssTokenName(COLLECTION_NAMES.layoutRole, property)});`;
  });
}

function modeSelectionBlock(selector: string, collectionName: string, mode: string, model: TokenModel, roots: Set<string>, filter?: (name: string) => boolean): string {
  return cssBlock(selector, modeDeclarations(collectionName, mode, model, roots, filter));
}

function modeDeclarations(collectionName: string, mode: string, model: TokenModel, roots: Set<string>, filter?: (name: string) => boolean): string[] {
  const collection = model.collection(collectionName);
  return collection ? collection.variables.filter((variable) => !filter || filter(variable.name)).map((variable) => {
    addValueReferences(model, roots, collectionName, variable.name, mode);
    return valueDeclaration(model.cssTokenName(collectionName, variable.name), valueToCss(collection, variable, variable.valuesByMode[mode], model, mode));
  }) : [];
}

function colorIntensityVariableFilter(usage?: RuntimeUsage): ((name: string) => boolean) | undefined {
  if (!usage) {
    return undefined;
  }
  const staticKinds = selectedStaticSurfaces(usage);
  const interactivePriorities = new Set(selectedInteractiveSurfaces(usage).map(([, options]) => options.priority));
  return (name) => {
    if (name.startsWith("local/")) {
      return true;
    }
    const staticKind = staticKinds.find((kind) => name.startsWith(`on-surface/static/${kind}/`));
    if (staticKind) {
      return true;
    }
    return Array.from(interactivePriorities).some((priority) => name.startsWith(`on-surface/interactive/${priority}/`));
  };
}

function colorToneVariableFilter(usage?: RuntimeUsage): ((name: string) => boolean) | undefined {
  if (!usage) {
    return undefined;
  }
  const colorFilter = colorIntensityVariableFilter(usage) as (name: string) => boolean;
  return (name) => {
    const separator = name.indexOf("/");
    return separator > 0 && usage.intensities.has(name.slice(0, separator) as (typeof COLOR_INTENSITIES)[number]) && colorFilter(name.slice(separator + 1));
  };
}

function layoutDensityVariableFilter(usage?: RuntimeUsage): ((name: string) => boolean) | undefined {
  return usage ? (name) => Array.from(usage.layoutRoles).some((role) => name.startsWith(`${role}/`)) : undefined;
}

function breakpointVariableFilter(usage?: RuntimeUsage): ((name: string) => boolean) | undefined {
  if (!usage) {
    return undefined;
  }
  return (name) => {
    if (name.startsWith("typography/")) {
      const publicName = `--${cssSlug(name)}`;
      if (usage.typographyVariables.has(publicName)) {
        return true;
      }

      const textStyleId = cssSlug(name.replace(/^typography\//, "").replace(/\/(line-height|size)$/, ""));
      return usage.textStyles.has("*") || usage.textStyles.has(textStyleId);
    }
    return Array.from(usage.layoutRoles).some((role) =>
      Array.from(usage.densities).some((density) => name.startsWith(`layout-role/${role}/${density}/`)));
  };
}

function selectedStaticSurfaces(usage?: RuntimeUsage): Array<"raised" | "sunken"> {
  return (["raised", "sunken"] as const).filter((kind) => !usage || usage.surfaceTypes.has(kind));
}

function selectedInteractiveSurfaces(usage?: RuntimeUsage) {
  return Object.entries(interactivePriority).filter(([surface]) => !usage || usage.surfaceTypes.has(surface as keyof typeof interactivePriority));
}

function selectedValues<T extends string>(values: readonly T[], selected?: ReadonlySet<T>): T[] {
  return selected ? values.filter((value) => selected.has(value)) : values.slice();
}

function activeModes<T extends string>(model: TokenModel, collectionName: string, supported: readonly T[]): T[] {
  const collection = model.collection(collectionName);
  return supported.filter((value) => collection?.modes.includes(value));
}

function addReference(roots: Set<string> | undefined, collection: string, name: string): void {
  roots?.add(tokenKey(collection, name));
}

function addValueReferences(model: TokenModel, roots: Set<string> | undefined, collection: string, name: string, mode: string): void {
  for (const key of tokenValueReferenceKeys(model.source, collection, name, mode)) {
    roots?.add(key);
  }
}

function valueDeclaration(name: string, value: string): string {
  return `  ${name}: ${value};`;
}

function cssBlock(selector: string, declarations: string[]): string {
  if (declarations.length === 0) {
    return "";
  }
  return `${selector} {\n${dedupeDeclarations(declarations).join("\n")}\n}`;
}

function indent(css: string): string {
  return css.split("\n").map((line) => `  ${line}`).join("\n");
}

function dedupeDeclarations(declarations: string[]): string[] {
  return Array.from(new Set(declarations));
}

function dedupeChunks(chunks: string[]): string[] {
  return Array.from(new Set(chunks.filter(Boolean)));
}

function declarationMap(declarations: string[]): Map<string, string> {
  return new Map(declarations.map((declaration) => [declarationName(declaration), declaration]));
}

function declarationName(declaration: string): string {
  return declaration.slice(0, declaration.indexOf(":")).trim();
}
