import type { StyleflowTokensFile } from "../format/index.js";
import { typographyTextStyles } from "./contractOutput.js";
import { cssSlug } from "./model.js";
import type { RuntimeUsage } from "./usage.js";

export function generateThemeCss(tokens?: StyleflowTokensFile, usage?: RuntimeUsage): string {
  const declarations = [
    "  --color-local-surface: var(--local-surface);",
    "  --color-local-surface-scrim: var(--local-surface-scrim);",
    "  --color-local-border: var(--local-border);",
    "  --color-local-border-soft: var(--local-border-soft);",
    "  --color-local-border-strong: var(--local-border-strong);",
    "  --color-local-border-accent: var(--local-border-accent);",
    "  --color-local-fg-primary: var(--local-foreground-primary);",
    "  --color-local-fg-secondary: var(--local-foreground-secondary);",
    "  --color-local-fg-tertiary: var(--local-foreground-tertiary);",
    "  --color-local-fg-muted: var(--local-foreground-muted);",
    "  --color-local-fg-accent: var(--local-foreground-accent);",
    "  --spacing-local-px: var(--local-px);",
    "  --spacing-local-py: var(--local-py);",
    "  --spacing-local-gap: var(--local-gap);",
    "  --radius-local: var(--local-radius);",
    "  --border-width-local: var(--local-border-width);",
    "  --container-local-container: var(--local-container-max-width);",
    "  --font-local-body: var(--typography-body-default-body-md-family);",
    "  --font-local-heading: var(--typography-heading-default-heading-2-family);",
    "  --font-weight-local-body: var(--typography-body-default-body-md-weight);",
    "  --font-weight-local-heading: var(--typography-heading-default-heading-2-weight);",
    "  --leading-local-body: var(--typography-body-default-body-md-line-height);",
    "  --leading-local-heading: var(--typography-heading-default-heading-2-line-height);"
  ];

  if (tokens) {
    for (const style of selectedThemeTextStyles(tokens, usage)) {
      const id = cssSlug(style.id);
      const prefix = cssSlug(style.tokenPrefix);
      declarations.push(`  --font-${id}: var(--typography-${prefix}-family);`);
      declarations.push(`  --text-${id}: var(--typography-${prefix}-size);`);
      declarations.push(`  --text-${id}--line-height: var(--typography-${prefix}-line-height);`);
      declarations.push(`  --font-weight-${id}: var(--typography-${prefix}-weight);`);
      declarations.push(`  --leading-${id}: var(--typography-${prefix}-line-height);`);
    }
  }

  return `/* Generated by StyleFlow. Tailwind v4 public bridge. */
@theme inline {
${declarations.join("\n")}
}
`;
}

function selectedThemeTextStyles(tokens: StyleflowTokensFile, usage?: RuntimeUsage): ReturnType<typeof typographyTextStyles> {
  const styles = typographyTextStyles(tokens);
  if (!usage || usage.textStyles.has("*")) {
    return styles;
  }
  return styles.filter((style) => usage.textStyles.has(style.id));
}
