import { isTransparentCollection } from "../contracts.js";
import type { StyleflowTokensFile } from "../format/index.js";
import { cssModeTokenName, cssTokenName, isAlias, TokenModel, tokenKey, valueToCss } from "./model.js";

/**
 * Genera il dump `tokens.css` legacy (per-mode + base). Usato solo in modalità
 * `output.legacyTokensCss`; il flusso di default elimina questo file e collassa
 * i layer alias direttamente in runtime/styleflow.css.
 */
export function generateTokensCss(tokens: StyleflowTokensFile, included?: ReadonlySet<string>, compact = false): string {
  const model = new TokenModel(tokens, { transparent: false });
  const declarations: string[] = [];
  for (const collection of tokens.collections) {
    for (const variable of collection.variables) {
      if (included && !included.has(tokenKey(collection.name, variable.name))) {
        continue;
      }
      if (compact) {
        declarations.push(`  ${cssTokenName(collection.name, variable.name)}: ${valueToCss(collection, variable, variable.valuesByMode[collection.modes[0]], model, collection.modes[0])};`);
        continue;
      }
      for (const mode of collection.modes) {
        declarations.push(`  ${cssModeTokenName(collection.name, variable.name, mode)}: ${valueToCss(collection, variable, variable.valuesByMode[mode], model, mode)};`);
      }
      declarations.push(`  ${cssTokenName(collection.name, variable.name)}: var(${cssModeTokenName(collection.name, variable.name, collection.modes[0])});`);
    }
  }
  return [
    "/* Generated by StyleFlow. Source variables and aliases. */",
    ":root {",
    ...declarations,
    "}",
    ""
  ].join("\n");
}

/**
 * Chiusura delle dipendenze alias a partire da `roots`. Con `transparent` (default)
 * le collezioni trasparenti (Primitives/OnSurfaceInteractive*) vengono attraversate
 * ma NON incluse nel set risultante: i loro target reali (es. SemanticColor) sì.
 */
export function tokenDependencyClosure(tokens: StyleflowTokensFile, roots: Iterable<string>, activeValuesOnly = false, transparent = true): Set<string> {
  const tokenByKey = new Map<string, {
    collection: StyleflowTokensFile["collections"][number];
    variable: StyleflowTokensFile["collections"][number]["variables"][number];
  }>();
  for (const collection of tokens.collections) {
    for (const variable of collection.variables) {
      const key = tokenKey(collection.name, variable.name);
      tokenByKey.set(key, { collection, variable });
    }
  }
  const selected = new Set<string>();
  const visited = new Set<string>();
  const pending: string[] = [];
  const enqueue = (key: string): void => {
    const token = tokenByKey.get(key);
    if (!token || visited.has(key)) {
      return;
    }
    visited.add(key);
    pending.push(key);
    if (!transparent || !isTransparentCollection(token.collection.name)) {
      selected.add(key);
    }
  };
  for (const key of roots) {
    enqueue(key);
  }
  while (pending.length > 0) {
    const key = pending.pop() as string;
    const token = tokenByKey.get(key);
    if (!token) {
      continue;
    }
    const values = activeValuesOnly
      ? [token.variable.valuesByMode[token.collection.modes[0]]]
      : Object.values(token.variable.valuesByMode);
    for (const value of values) {
      if (!isAlias(value)) {
        continue;
      }
      enqueue(tokenKey(value.alias.collection, value.alias.name));
    }
  }
  return selected;
}

export function tokenValueReferenceKeys(tokens: StyleflowTokensFile, collectionName: string, variableName: string, mode?: string): string[] {
  const collection = tokens.collections.find((item) => item.name === collectionName);
  const variable = collection?.variables.find((item) => item.name === variableName);
  if (!collection || !variable) {
    return [];
  }
  const values = mode ? [variable.valuesByMode[mode]] : Object.values(variable.valuesByMode);
  return values
    .filter(isAlias)
    .map((value) => tokenKey(value.alias.collection, value.alias.name));
}
