import {
  COLOR_INTENSITIES,
  COLOR_TONES,
  INTERACTION_STATES,
  LAYOUT_DENSITIES,
  LAYOUT_ROLES,
  SURFACE_TYPES,
  THEME_MODES
} from "../contracts.js";
import type { StyleflowTokensFile } from "../format/index.js";
import { typographyTextStyles } from "./contractOutput.js";

export function generateTypesOutput(tokens: StyleflowTokensFile): string {
  const modes = (collection: string, supported: readonly string[]) =>
    tokens.collections.find((item) => item.name === collection)?.modes.filter((mode) => supported.includes(mode)) ?? [];
  const tones = modes("ColorTone", COLOR_TONES);
  const intensities = modes("ColorIntensity", COLOR_INTENSITIES);
  const roles = modes("LayoutRole", LAYOUT_ROLES);
  const densities = modes("LayoutRoleDensity", LAYOUT_DENSITIES);
  const themes = modes("SemanticColor", THEME_MODES);
  const textStyles = typographyTextStyles(tokens).map((style) => style.id);
  return `/* Generated by StyleFlow. */
export type ColorTone = ${union(tones)};
export type ColorIntensity = ${union(intensities)} | ${intensities.join(" | ")};
export type LayoutRole = ${union(roles)};
export type LayoutDensity = ${union(densities)};
export type ThemeMode = ${union(themes)};
export type SurfaceType = ${union(SURFACE_TYPES)};
export type InteractionState = ${union(INTERACTION_STATES)};
export type TextStyleId = ${union(textStyles)};
`;
}

function union(values: readonly string[]): string {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}
